# Generated by Django 4.0.6 on 2022-09-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_registration_no', models.CharField(max_length=12)),
                ('Surname', models.CharField(max_length=12)),
                ('Other_name', models.CharField(max_length=12)),
                ('DOB', models.DateTimeField()),
                ('parent_ID', models.PositiveIntegerField()),
                ('immunization_type', models.CharField(max_length=12)),
                ('immunization_dose_no', models.CharField(max_length=12)),
                ('immunization_description', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_ID', models.PositiveIntegerField()),
                ('child_registration_no', models.CharField(max_length=12)),
                ('immunization_dose_no', models.CharField(max_length=12)),
                ('immunization_description', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_ID', models.PositiveIntegerField()),
                ('father_id', models.PositiveIntegerField()),
                ('Surname', models.CharField(max_length=12)),
                ('Other_name', models.CharField(max_length=12)),
                ('DOB', models.DateTimeField()),
                ('Village', models.CharField(max_length=12)),
                ('Ward', models.CharField(max_length=12)),
                ('child_registration_no', models.CharField(max_length=12)),
                ('Mobile_No', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_ID', models.PositiveIntegerField()),
                ('Surname', models.CharField(max_length=12)),
                ('Other_name', models.CharField(max_length=12)),
                ('DOB', models.DateTimeField()),
                ('Mobile_No', models.PositiveIntegerField()),
                ('Job_description', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_id', models.CharField(max_length=50, null=True)),
                ('vaccine_name', models.CharField(max_length=50, null=True)),
                ('vaccine_type', models.CharField(max_length=50)),
                ('vaccine_quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
