# Generated by Django 4.0.6 on 2022-09-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='vaccine_type',
            field=models.CharField(choices=[('BCG', 'BCG'), ('OPV', 'OPV'), ('Rotavirus', 'Rotavirus'), ('Pneumo_Conj', 'Pneumo_Conj'), ('DTWPHibHepB', 'DTWPHibHepB'), ('IPV', 'IPV'), ('YF', 'YF'), ('Measles', 'Measles'), ('HPV', 'HPV')], max_length=50),
        ),
    ]
