# Generated by Django 4.0.6 on 2022-09-14 10:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_rename_profile_profile1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile1',
            new_name='Profile',
        ),
    ]
