# Generated by Django 4.0.6 on 2022-09-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile1',
        ),
    ]
