# Generated by Django 4.0.6 on 2022-09-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_profile1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccine',
            old_name='vaccine_name',
            new_name='mode_of_admission',
        ),
    ]
